[workspace]
members = [
  "exc-util",
  "exc-custom",
  "exc-simu",
  "exc-dex",
  "exc-dydx",
  "exc-okx",
  "exc-bybit",
  "exc-gate",
  "exc-binance",
  "exc-bitget",
  "exc-mexc",
  "exc-kcex",
  "exc-bitunix",
]
resolver = "2"

[patch.crates-io]
exc-core = {git="https://github.com/rise0chen/exc", branch="rise"}
